Задание 3.1
htmlacademy-ecmascript/1347475-big-trip-14 pull request #5
Opened 2021-04-14 16:49 UTC by ddlein

2021-04-14 22:39 UTC, dtsaryov requested changes

2021-04-14 22:39 UTC, dtsaryov commented on src/view/edit-form.js
> +// export {createEditFormTemplate};
Закомментированный код не забываем удалять

2021-04-14 22:39 UTC, dtsaryov commented on src/view/edit-form.js
> +export default class WaypointEdit {
https://up.htmlacademy.ru/ecmascript/14/criteries#b27

2021-04-14 22:39 UTC, dtsaryov commented on src/utils.js
> +const render = (container, element, place) => {
Давай укажем значение по умолчанию для аргумента `place`

2021-04-14 22:39 UTC, dtsaryov commented on src/main.js
> +    if (evt.key === 'Escape' || evt.key === 'Esc') {
Эту проверку давай в utils утащим

2021-04-14 22:39 UTC, dtsaryov commented on src/view/edit-form.js
> +export default class WaypointEdit {
В остальных местах тоже проверь

2021-04-15 03:39 UTC, ddlein commented on src/view/edit-form.js
> +// export {createEditFormTemplate};
ok

2021-04-15 03:44 UTC, ddlein commented on src/utils.js
> +const render = (container, element, place) => {
ok

2021-04-15 04:17 UTC, ddlein commented on src/view/edit-form.js
> +export default class WaypointEdit {
ok

2021-04-15 04:29 UTC, ddlein commented on src/main.js
> +    if (evt.key === 'Escape' || evt.key === 'Esc') {
ok

2021-04-15 18:36 UTC, dtsaryov approved these changes

2021-04-15 18:36 UTC, dtsaryov commented on src/utils.js
> +// const onEscKeyDown = (evt, replace) => {
А это зачем оставил?)

2021-04-15 18:36 UTC, merged